export const WORK_LIST_REQUEST = 'WORK_LIST_REQUEST'
export const WORK_LIST_SUCCESS = 'WORK_LIST_SUCCESS'
export const WORK_LIST_FAIL = 'WORK_LIST_FAIL'


export const WORK_DETAILS_REQUEST = 'WORK_DETAILS_REQUEST'
export const WORK_DETAILS_SUCCESS = 'WORK_DETAILS_SUCCESS'
export const WORK_DETAILS_FAIL = 'WORK_DETAILS_FAIL'